# Generated by Django 6.0.1 on 2026-01-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, help_text='США, USA, Amerika, Америка, Россия, Russia, Rus', max_length=255),
        ),
    ]
